#!/bin/bash

# sync_issues.sh - Syncs issues.json to GitHub
JSON_FILE="issues.json"

if [ ! -f "$JSON_FILE" ]; then
    echo "❌ Error: $JSON_FILE not found."
    exit 1
fi

# --- GIT & REMOTE INITIALIZATION ---
if [ ! -d ".git" ]; then
    echo "🗂️  Initializing git repository..."
    git init
fi

# gh needs at least one commit to push a branch
if ! git rev-parse HEAD >/dev/null 2>&1; then
    echo "📝 Creating initial commit..."
    git add "$JSON_FILE"
    git commit -m "chore: initial project structure and issues"
fi

if ! gh repo view >/dev/null 2>&1; then
    echo "🌐 No remote found. Creating GitHub repository..."
    REPO_NAME=$(jq -r '.project' "$JSON_FILE" | tr '[:upper:]' '[:lower:]')
    
    # Using --confirm=false if you want it fully automated, 
    # but the defaults here should work.
    gh repo create "$REPO_NAME" --public --source=. --remote=origin --push
    echo "✅ Remote created: $REPO_NAME"
else
    echo "✅ GitHub remote detected."
fi
# -----------------------------------

# 1. Ensure Labels Exist
echo "🏷️  Checking labels..."
LABELS=("MVP" "Swift" "Wasm" "Cybernetic")
for label in "${LABELS[@]}"; do
    # -w is the standard flag for 'whole word' across BSD/macOS and GNU
    if ! gh label list --limit 100 | grep -qw "$label"; then
        echo "➕ Creating label: $label"
        gh label create "$label" --color "0052cc" --description "ECME Project Label"
    fi
done

# 2. Parse and Create Issues
echo "🚀 Syncing issues..."
jq -c '.issues[]' "$JSON_FILE" | while read -r issue; do
    TITLE=$(echo "$issue" | jq -r '.title')
    ID=$(echo "$issue" | jq -r '.id')
    CONTEXT=$(echo "$issue" | jq -r '.context')
    BG=$(echo "$issue" | jq -r '.background')
    DOD=$(echo "$issue" | jq -r '.definition_of_done')
    # Use empty string if no dependencies found
    DEPS=$(echo "$issue" | jq -r '.dependencies | join(", ") // ""')
    
    # Check if issue already exists (silencing the "no git remotes" noise)
    if gh issue list --search "$TITLE" 2>/dev/null | grep -q "$TITLE"; then
        echo "⏭️  Skipping: $TITLE (Already exists)"
        continue
    fi

    # Construct Body
    BODY="## Context
$CONTEXT

## Background
$BG

## Dependencies
${DEPS:-None}

## Definition of Done
$DOD

---
*Generated by ECME sync_issues.sh*"

    echo "📝 Creating issue: [$ID] $TITLE"
    # Added 2>/dev/null to the create command to keep output clean 
    # of the 'no git remotes' warning if gh is still warming up.
    gh issue create --title "[$ID] $TITLE" --body "$BODY" --label "MVP,Swift" >/dev/null
done

echo "✅ Sync complete."